#ifndef MFCPP_SOUNDENUM_HPP
#define MFCPP_SOUNDENUM_HPP

enum class SoundID {
    //GAME
    GAME_JUMP,
    GAME_BUMP,
    GAME_BREAK,
    GAME_COIN,
    GAME_STOMP,
    GAME_POWERUP,
    GAME_VINE,
    GAME_KICK2,
    GAME_PIPE,
    GAME_KICK3,
    GAME_KICK4,
    GAME_KICK5,
    GAME_KICK6,
    GAME_KICK7,
    GAME_KICK8,
    GAME_1UP,
    GAME_HAMMER,
    GAME_FIREBALL,
    GAME_BULLET1,
    GAME_BULLET2,
    GAME_BULLET3,
    GAME_TIMEOUT,
    GAME_THROW,
    GAME_STUN,
    GAME_CHILUN,
    GAME_VOLCANO,
    //EDITOR
    EDITOR_PLACE,
    EDITOR_DELETE,
    EDITOR_SWITCH,
    EDITOR_MENU,
    EDITOR_CLOSE,
    EDITOR_TAB_SELECT
};

#endif //MFCPP_SOUNDENUM_HPP
